# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moneybox-AndrewZandtValentine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moneybox-AndrewZandtValentine
    pod 'SnapKit', '~> 5.0.0'
    pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'Moneybox-AndrewZandtValentineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Moneybox-AndrewZandtValentineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
